### ISSUE TITLE
mod updating semi-borked

### ISSUE THREAD

**Issue by RobinNorling** [Kloct/tera-client#10]
Mods seem to update just fine but doesn't actually reload the newly updated mods before connecting to the game, thus requires a restart every time a mod is updated.

Happens on both my Ubuntu 16.04 machines, maybe i borked something too? Might need further investigating.

**Comment by PatrickSantoZZ** [comment]
no thats the normal updater problem from Pinkie Proxy , my idea was a "update mode" for CLI. :3 
you need to restart the client for every update.

**Comment by Kloct** [comment]
I'm guessing this is all in the dev branch.
I just pushed a fix 026a621
Hopefully it resolves the issue

**Comment by Kloct** [comment]
Looks like it does. Closing this issue 👍
