### ISSUE TITLE
dispatch.addDefinition doens't work

### ISSUE THREAD

**Issue by Hack-y** [Kloct/tera-client#21]
Hello, i'm trying to use `mod.dispatch.addDefinition(name, version, file);` but i already have error.

My code (work perfectly with Caali proxy):
`mod.dispatch.addDefinition(S_RESULT_EVOLUTION, 99, path.join(mod.rootFolder, 'defs', 'S_RESULT_EVOLUTION.99.def'));`

In CLI version,  I manage to log in the dispatch protocol file, but i have always error when mod load:
`Error: [tera-proxy-game] Error: [dispatch] hook: definition not found (S_RESULT_EVOLUTION.99)`

I try with other def, not working too ! Can someone help me please?

Thank

**Comment by Hack-y** [comment]
Hum i tried something...

If i do `mod.dispatch.addDefinition('S_RESULT_EVOLUTION', 99, path.join(mod.rootFolder, 'defs', 'S_RESULT_EVOLUTION.99.def'), true);` this work.

But if i do 

```
const	fs = require('fs'),
	path = require('path');

module.exports = function test(mod) {
	install()
	function install() {
		fs.readdirSync(path.join(mod.rootFolder, 'defs')).forEach(file => {
			let f = /^(.+?)\.(\d+)\.def$/.exec(file);
			console.log(f);
			mod.dispatch.addDefinition(f[1], f[2], path.join(mod.rootFolder, 'defs', f[0]), true);
		});
	}
}
```
doesn't work. I'm using synchrone fs so i need your help. Thank

**Comment by Kloct** [comment]
Strange 🤔 your functions seems to work fine for me
Are you sure you're running in toolbox mode?
You have to have a module.json file in the mod's root directory for the mod loader to know that it's a toolbox module.

I used a different def but here's what I got with just a simple copy paste of your code.
```
10:37:48 Info: [tera-proxy-game] Loading Add-Def (compat)
[
  'C_ADMIN.99.def',
  'C_ADMIN',
  '99',
  index: 0,
  input: 'C_ADMIN.99.def',
  groups: undefined
]
```

**Comment by Kloct** [comment]
Apparently the packet version has to be an integer.
`mod.dispatch.addDefinition(f[1], parseInt(f[2]), path.join(mod.rootFolder, 'defs', f[0]), true);`
If it works in toolbox like this though then that'll be something to change upstream. I'll see if I can fix it in tera-proxy-game but for now `parseInt()` should work in both toolbox and tera-client 👍

**Comment by Hack-y** [comment]
Ho right.... i didn't notice this. Thank your this work fine now ;)
