### ISSUE TITLE
EU

### ISSUE THREAD

**Issue by NetworkStream** [Kloct/tera-client#6]
ty for the Awesome work , but i have a  gameforge master account has two sub account ,account X have char X1 and account Y have char Y1 , the problem is i cant select account Y nor char Y1 , any idea ?

**Comment by Kloct** [comment]
I had no clue that you could even have two game accounts associated with the same Gameforge account lol. I'll see what I can do to fix it.

I think right [here](https://github.com/Kloct/tera-auth-ticket/blob/1787636e6c9d6ea31888971952ca7fba48556982/regions/eu.js#L77) is where is just selects the first account that matches 'tera'

**Comment by NetworkStream** [comment]
yea its worked ty @Kloct , here what i did
                   ` let account = Object.values(body).find(a=>{
                        if (a.guls.game === 'tera'&&a.displayName==AccDisplayName){
                            return true;
                        }
                    });
`
