### ISSUE TITLE
no auth mechanism defined

### ISSUE THREAD

**Issue by Mattax-Gokoro** [Kloct/tera-client#7]
http://prntscr.com/qi9bkm
Keep getting this problem

**Comment by Kloct** [comment]
Looks like incorrect login credentials
Double check your email and password and also check that the account isn't banned or blocked in some way.

That error will occur if you were not able to obtain authorization after sending a login request to Gameforge.

I'll write a handler for that error so it's not quite as ambiguous in the future.
