### ISSUE TITLE
Client stuck at logging onto char

### ISSUE THREAD

**Issue by eduedp** [Kloct/tera-client#9]
My client always stuck at this point. I've tried other accs also...
Is this normal? Does that means its logged in?

> 19:21:32 Info: [client] NA -> velika | v99.01 (protocol 359960)
> 19:21:32 Info: [client] Checking for updates
> 19:21:32 Info: [client] Client is up to date
> 19:21:33 Info: [mod-manager] Verified 1 package in 2ms
> 19:21:33 Info: [mod-manager] Checking for mod updates
> 19:21:33 Info: [mod-manager] Update checked 1 mod in 268ms
> 19:21:37 Info: [tera-auth-ticket] Received Access Token!
> 19:21:37 Info: [tera-auth-ticket] Account Info: (Account Name: xxxxxx, Account Id: xxxxxx)
> 19:21:38 Info: [tera-auth-ticket] Got Auth Ticket!
> 19:21:38 Info: [client] connected to 208.67.49.53:10001
> 19:21:39 Info: [tera-proxy-game] Detected protocol version 359960 - patch 88.05
> 19:21:39 Info: [tera-proxy-game] Loading game
> 19:21:39 Info: [tera-proxy-game] Loaded 1 mod in 3ms
> 19:21:39 Info: [client] logging onto xxxxxx [Popori Sorcerer / 47] (id: xxxxxxx)

**Comment by Kloct** [comment]
Yep it's logged in.
There would be an error if it failed.
You should be able to run whatever scripts you want from that point 👍
